language: python
python:
    - "2.7"

install:
    - pip install -r requirements.txt
    - pip install pytest-cov
    - pip install codecov
script:
    - cd tests
    - pytest --cov=./
after_success:
    - codecov
