
version: 0.1
log:
  level: debug
storage:
  oss:
    accesskeyid: QFmrMPB18qNx9KYc
    accesskeysecret: IuAdh4qL9noDf0UnMOO977HSgZSc0E
    region: oss-cn-beijing
    bucket: jbiobio
    rootdirectory: dockers
    secure: false
    internal: false
http:
  addr: 0.0.0.0:5000

